### ISSUE TITLE
The validator message is not working

### ISSUE THREAD

**Issue by savandev17** [davidwalschots/angular-reactive-validation#13]
Dear Sir,
I am using Angular version 11, The validator message is not working, after I inspected on browser found property (display: none) inside class ".invalid-feedback", if I unchecked it will working find

![image](https://user-images.githubusercontent.com/34710166/99259301-5f835480-284c-11eb-98bd-a843cf204386.png)

Thank you.

**Comment by davidwalschots** [comment]
Hello @savandev17,

Thank you for opening an issue. The `angular-reactive-validation` package doesn't contain CSS styles for the `invalid-feedback` class other than the example implementation which doesn't contain `display: none;`.

It is up to developers using the package to define the styles that are right for them. Likely somewhere you have declared `display: none;` for the given class. Please try to search for `invalid-feedback` inside of your project and see if you can find `display: none;` anywhere 😃.

Kind regards,

David

**Comment by savandev17** [comment]
Thank you for your recommendation.
