### ISSUE TITLE
'arv-validation-messages' is not a known element

### ISSUE THREAD

**Issue by MauDagos** [davidwalschots/angular-reactive-validation#15]
Hello! I've just tried incorporating this library into my project. I've followed the steps in the readme, but I'm getting this error:

```
    ERROR in src/app/external/pages/get-started/get-started.component.html:24:13 - error NG8001: 'arv-validation-messages' is not a known element:
    1. If 'arv-validation-messages' is an Angular component, then verify that it is part of this module.
    2. If 'arv-validation-messages' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

    24             <arv-validation-messages for="phoneNumber"></arv-validation-messages>
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      src/app/external/pages/get-started/get-started.component.ts:13:16
        13   templateUrl: './get-started.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component GetStartedComponent.
```

I started learning Angular just a few days ago, so I'm really lost when it comes to this error. Many thanks in advance! I'm really looking forward to getting this library working.

**Comment by davidwalschots** [comment]
Hi @MauDagos. It's important to import the `ReactiveValidationModule` in the module where you declare your `GetStartedComponent`. You're most likely missing that import. If that doesn't solve your problem you'll have to share more code. 😀

**Comment by MauDagos** [comment]
Oh! Ok, I was importing it in the wrong module. Thank you!
