### ISSUE TITLE
Using angular-reactive-validation alongside ng-otp-input

### ISSUE THREAD

**Issue by MauDagos** [davidwalschots/angular-reactive-validation#16]
Hello! I'm struggling to get `angular-reactive-validation` working with `ng-otp-input`, specifically I'm unable to get `<arv-validation-message>` to display a validation message when the one-time password (otp) is empty not below a certain length.

Skimmed relevant component code:
```typescript
import { Component } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Validators } from 'angular-reactive-validation';

@Component({
    selector: 'app-code',
    templateUrl: './code.component.html',
    styleUrls: ['./code.component.scss']
})
export class CodeComponent {
    codeForm: FormGroup;
    config = {
        allowNumbersOnly: true,
        length: 4
    }

    constructor(
        private _formBuilder: FormBuilder) {
        var codeLength = this.config.length;
        var invalidMsg = `Please fill out all ${codeLength} characters`;

        this.codeForm = this._formBuilder.group({
            code: ['', [Validators.required(invalidMsg),
                Validators.minLength(codeLength, invalidMsg)]]
        });
    }

    onCodeChange(code: string) {
        this.codeForm.patchValue({ code: code });
        this.codeForm.markAllAsTouched();
    }

    public async submit(codeData: { code: string }) {
        var code = codeData.code;

        // do stuff
    }
}
```

Skimmed relevant HTML:
```html
<div>
    <form [formGroup]="codeForm"
        (ngSubmit)="submit(codeForm.value)">
        <ng-otp-input (onInputChange)="onCodeChange($event)"
            [config]="config"
            (keyup.enter)="codeForm.valid && submit(codeForm.value)">
        </ng-otp-input>
        <arv-validation-message [for]="codeForm.get('code')"></arv-validation-message>
        <button type="submit"
            [disabled]="!codeForm.valid">
            Continue
        </button>
    </form>
</div>
```

I can't specify `formControlName` to `ng-otp-input` (I get a `No value accessor for form control` error), so I'm working around it by:

1. Supplying FormControl instances to `arv-validation-messages`, i.e. `<arv-validation-message [for]="codeForm.get('code')">`.
2. When the OTP is changed, I'm marking the form's control as touched, since in `angular-reactive-validation`'s github it says:
> By default validation messages are displayed when the associated control is touched,

What am I missing for my workaround to work?

**Comment by MauDagos** [comment]
I forgot to mention that with my workaround the form functions correctly except displaying the validation messages. That's the problem at hand.

**Comment by davidwalschots** [comment]
`ng-otp-input` doesn't implement the [ControlValueAccessor](https://angular.io/api/forms/ControlValueAccessor) interface and therefore doesn't work properly with Angular forms. Request the contributors of `ng-otp-input` implement that interface, or make a contribution to that project 🙂.

**Comment by MauDagos** [comment]
Understood. Thanks for the kind suggestions 👍
