### ISSUE TITLE
Version 9.0.0 unavailable

### ISSUE THREAD

**Issue by diversifiedfinancial** [davidwalschots/angular-reactive-validation#55]
I happened to be looking for this upgrade for angular version 15 and happened to find version 9.0.0 of angular-reactive-validation published '1 minute ago'.  I'd never seen that before.  But I can't get it installed.  
@
Is there a build/publish process that happens before the new version is generally available to pull down?  Does it need to propagate out?  Or is there possibly a problem with the published package?  It's now been more than an hour and I'm still unable to install it with either @latest or @9.0.0 and I see that the download count is still 0.  Any ideas @davidwalschots or @jafin?

Please help.  
Thanks.

**Comment by davidwalschots** [comment]
Thanks for letting me know. It seems there's an issue with the `rxjs` peer dependency declaration. I'll work on a fix.

**Comment by davidwalschots** [comment]
I've just released `9.0.1` which solves the problem.

**Comment by diversifiedfinancial** [comment]
Thank you.
